### ISSUE TITLE
Wired blank on foreground apps.

### ISSUE THREAD

**Issue by LiangyuLiu** [EliverLara/Ant-Nebula#10]
Hi,  I am using fedora 31 workstation and love this theme a lot. However, my foreground program turns grey and some icons are blank.  
Gnome Version 3.34.2.
![image](https://user-images.githubusercontent.com/48219971/71328101-50324480-24df-11ea-882a-78195292ce37.png)

**Comment by EliverLara** [comment]
Does this still persist?
