### ISSUE TITLE
(Slim) Missing exit button when focus.

### ISSUE THREAD

**Issue by Neutrovertido** [EliverLara/Ant-Nebula#14]
Some non-gtk apps do not have an exit button when they are given focus.
(i.e: discord, vlc, simplenote)

![imagen](https://user-images.githubusercontent.com/61665012/96607106-3e632e80-12b5-11eb-801e-9099f6522fcd.png)

But when focus is lost, it's still there.

![imagen](https://user-images.githubusercontent.com/61665012/96607165-5044d180-12b5-11eb-8f39-40b4e2f190f4.png)

**Comment by EliverLara** [comment]
Hi, I'm not able to reproduce the issue on my side: 

![Captura de pantalla de 2020-10-21 13-12-30](https://user-images.githubusercontent.com/9838260/96763135-2962ca00-139f-11eb-82dc-b74eb9f36700.png)

Could you provide more info about you OS, please?

**Comment by Neutrovertido** [comment]
It seemed to be a temporary issue, it stopped happening later.
![imagen](https://user-images.githubusercontent.com/61665012/96800210-08f83700-13c2-11eb-952b-12dbf8560326.png)
