### ISSUE TITLE
Can't see text inside menus in wingpanel

### ISSUE THREAD

**Issue by pietrofxq** [EliverLara/Ant-Nebula#2]
Using Ant-Nebula:
![image](https://user-images.githubusercontent.com/6238029/36598977-a1049cca-188c-11e8-8540-fe42dababae3.png)

Using Ant:

![image](https://user-images.githubusercontent.com/6238029/36599001-b51f9138-188c-11e8-8a23-a7280c2eb7e2.png)

**Comment by pietrofxq** [comment]
Thanks for fixing, I downloaded the master branch but the theme is broken :/

**Comment by EliverLara** [comment]
HI, I downloaded the master branch to verify it but everything looks fine, the theme is applied correctly, make sure you apply the theme correctly since when you download from github, the extracted folder is renamed to Ant-Nebula-master.

**Comment by pietrofxq** [comment]
Hi, my bad, I copied the folder to /themes without the original permissions. Now it's working, but the system title bar is white:

![image](https://user-images.githubusercontent.com/6238029/36623468-c9334a82-18e3-11e8-95b2-9ec5e3709dd9.png)

Can you confirm this bug?

Thanks

**Comment by pietrofxq** [comment]
Hi, my bad - I copied the folder without the original permissions. Everything looks good - thanks!

**Comment by pietrofxq** [comment]
Do you know if the white text inside file picker is a bug of theme?

![image](https://user-images.githubusercontent.com/6238029/36625105-e1394064-18f7-11e8-965e-f0e1e0484ea3.png)

**Comment by EliverLara** [comment]
Thanks for reporting!, that's fixed.
