### ISSUE TITLE
Glitchy behaviour with the window buttons with Display Scaling

### ISSUE THREAD

**Issue by stevengubler** [EliverLara/Ant-Nebula#3]
# The Issue
My laptop has a HiDPI 4k display, so I have my display scaling set to 200%. This is causing an issue where the window buttons are showing up incorrectly.

![image](https://user-images.githubusercontent.com/9147580/41005099-67de8152-68d9-11e8-834f-03123c7ec2b8.png)

When I turn off display scaling, the buttons appear normally.

# Other notes
Inactive windows show nothing

![image](https://user-images.githubusercontent.com/9147580/41005302-20284ac2-68da-11e8-8250-e78da9c86ae5.png)
 
There is also a hard to capture vertical stretching issue where the buttons will stretch vertically to the length of the window top bar when ever the window receives or loses focus. The buttons will quickly disappear after that if the window is losing focus, or unstretch if the window is gaining focus.

**Comment by stevengubler** [comment]
Also, the buttons do function as normal. They are just invisible/the wrong size/stretched

**Comment by EliverLara** [comment]
Hi thanks for reporting, the issue was also reported on the original Ant theme, please [check it](https://github.com/EliverLara/Ant/issues/9) for more details.

**Comment by EliverLara** [comment]
Fixed in last commit.
