### ISSUE TITLE
Ant Nebula Issue

### ISSUE THREAD

**Issue by venkatesh27das** [EliverLara/Ant-Nebula#4]
I am currently facing issue while opening any folder from VS Code.
Like when you go to file explorer in File->Open Folder and the file explore opens and is blank.
Check out the issue.

**Comment by shahlin** [comment]
I'm having the same issue

**Comment by JuanCAlpizar** [comment]
![image](https://user-images.githubusercontent.com/2028118/54971099-922b5b80-4f4a-11e9-9b90-6c903e48d5b1.png)
Not sure if the issue has been solved for you guys, but I'm seeing no issue at all with the latest stable version, do you still have the same issue @venkatesh27das  ?

**Comment by shahlin** [comment]
@JuanCAlpizar Just checked, the problem is fixed now
