### ISSUE TITLE
GNOME Shell notifications are difficult to read

### ISSUE THREAD

**Issue by torqueyy** [EliverLara/Ant-Nebula#5]
OS: Fedora 29
GNOME Version: 3.30.2

This example used a transfer from GSConnect. The white "Transfer Successful" is fine, but the details which appear below are black over a dark background, and so are hard to read. Screenshot attached.
![screenshot from 2018-11-27 22-42-11](https://user-images.githubusercontent.com/40131158/49072781-e4f35000-f295-11e8-8b12-2970791119a5.png)

**Comment by EliverLara** [comment]
Hi,, thanks for reporting!, I also have a Fedora 29 with gnome 3.30.2 and everything looks good for me:

![nebula](https://user-images.githubusercontent.com/9838260/49116538-86ad7980-f263-11e8-8f98-14c9afd0da01.png)

Could you check that this is not a conflict with another gdm theme? that's what usually happens in this situation, as you can see [here](https://github.com/EliverLara/Sweet/issues/15) and [here](https://github.com/EliverLara/Sweet/issues/6).

**Comment by torqueyy** [comment]
Ah, that helps a lot! I installed the Materia GDM theme but I didn't know it could affect the shell theme too.

Thanks so much. Happy to have this marked as closed.

-------- Original Message --------
